version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    environment:
      - NODE_ENV=development

  test:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test

  test-watch:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test -- --watch 